# Generated by Django 5.1.8 on 2025-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_foodmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='image_url',
            field=models.URLField(max_length=5000),
        ),
    ]
